In [7]:
np1 = np.array([x for x in range(10)] )
np1

In [15]:
 import math
print(math.sqrt(4))

2.0


In [19]:
#multim=dimensional arrays
np0=np.array([2])
np1=np.array([2,3,4])
np2=np.array([[2,4,6],[45,7,8]])
np3=np.array([[[2,4,6],[45,7,8]],[[6,8,0],[2,8,4]]])
print(np0)
print(np1)
print(np2)
print(np3)

print(np0.ndim)
print(np1.ndim)
print(np2.ndim)
print(np3.ndim)
sumnp= np2 + np1
print(sumnp)

[2]
[2 3 4]
[[ 2  4  6]
 [45  7  8]]
[[[ 2  4  6]
  [45  7  8]]

 [[ 6  8  0]
  [ 2  8  4]]]
1
1
2
3
[[ 4  7 10]
 [47 10 12]]


In [18]:
#Array manipulation function

np0=np.array([2])
np1=np.array([2,3,4])
np2=np.array([[2,4,6],[45,7,8]])
np3=np.array([[[2,4,6],[45,7,8]],[[6,8,0],[2,8,4]]])
print(np0.shape)
print(np1.shape)
print(np2.shape)
print(np3.shape)
np_concat = np.concatenate((np0 ,np1))
np_concat
print(np_concat.reshape(2,2))

#numpy arithmetic fn

print(np.add(np1,np0))
print(np.subtract(np1,np0))
print(np.mod(np1,np0))

#numpy statistical fn

print(np.median(np2))
print(np.mean(np2))
print(np.average(np2))

(1,)
(3,)
(2, 3)
(2, 2, 3)
[[2 2]
 [3 4]]
[4 5 6]
[0 1 2]
[0 1 0]
6.5
12.0
12.0


In [17]:
#numpy string functions
a = ["hello","HOW", "you"]
print(a)
b = np.array(["hi","where","you"])
print(b)
c = np.char.add(a,b)
print(c)

d= "Hello how are guy?"
print(d)
e = np.char.replace(d,'Hello','ash')
print(e)

print(np.char.upper(d))
print(np.char.lower(d))
d= "Hello how are guy?"
e = np.char.replace(d,'Hello','ash')
print(e)


['hello', 'HOW', 'you']
['hi' 'where' 'you']
['hellohi' 'HOWwhere' 'youyou']
Hello how are guy?
ash how are guy?
HELLO HOW ARE GUY?
hello how are guy?
ash how are guy?


In [24]:
#Array indexing
import numpy as np
a0 = np.array([2])
a1 = np.array([2,3,6])
a2 = np.array([[2,3,4],[5,67,8],[4,6,0]])
a3 = np.array([[[2,3,4],[5,67,8],[4,6,0]],[[2,4,6],[5,7,9],[6,1,34]],[[2,87,34],[67,67,88],[44,63,30]]])
vhc = np.array([['car','bus','Rowboat','Bicycle'], 
['train','flight','Truck', 'Ship']])

print(a0[0])
print(a1[1])
print(a2[2,1])
print(a3[1,1,2])
print(a3[-2,-2,-1])

2
3
6
9
9


In [13]:
#slicing
import numpy as np
np1 = np.array([x for x in range(10)])
np2 = np.array([1,3,5,6,7,5,78])
a2 = np.array([[2,3,4,6,8,9],[6,5,43,5,67,8],[4,6,7,34,6,0]])
n = np.arange(1,7,2)
print(n)
print(np.arange(3,9,0.5))
print(np.linspace(1,5,10))
print(np2[1:6])
print(np2[1:6:2])
print(a2[0,1:4])
print(a2[2,3:])
print(np1[3:-1])
print(np2[1:-3])

[1 3 5]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[3 5 6 7 5]
[3 6 5]
[3 4 6]
[34  6  0]
[3 4 5 6 7 8]
[3 5 6]


In [66]:
#Random function
import random
import numpy as np
print(np.random.random())
print(np.random.randn(2,3))
print(np.random.randint(2,8))
random_no = random.randint(1,6)
print("the random no is %s" %(random_no))
print(np.random.randint(2,8,(2,2)))
for i in range(5) : 
    random.seed(13)
print(random.randint(1,50))

0.2652991708837562
[[-0.89206622 -1.2053281  -0.26636721]
 [-0.45670744  1.23419535  0.48856558]]
3
the random no is 1
[[4 4]
 [6 4]]
17


In [12]:
#reshape and ravel fn
import numpy as np
a= np.arange(12)
print(a)
print(np.reshape(a,(3,4)))
a2 = np.array([[2,3,4,6,8,9],[6,5,43,5,67,8],[4,6,7,34,6,0]])
print(np.ravel(a2))
print(type(a2))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  3  4  6  8  9  6  5 43  5 67  8  4  6  7 34  6  0]
<class 'numpy.ndarray'>
